# Workflow para desplegar la aplicación Ionic/Angular a GitHub Pages
name: Deploy to GitHub Pages

# Ejecutar en push a main y en pull requests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Permisos necesarios para GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Solo permitir un deployment concurrente
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job para construir la aplicación
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
      
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Instalar dependencias
      run: npm ci --legacy-peer-deps
      
    - name: Lint del código
      run: npm run lint
      
    - name: Ejecutar tests
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
      
    - name: Construir aplicación para producción
      run: npm run build:gh-pages
      
    - name: Configurar Pages
      uses: actions/configure-pages@v4
      
    - name: Subir artefacto de build
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'www'

  # Job para desplegar a GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Desplegar a GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
